<?php

use Zend\Session\Container;

$sessionLogin = new Container('credo');
?>
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Vehicle Brands </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <a href="<?php echo $this->url('admin-vehicle-brands', array('action' => 'index')); ?>">
                        <li class="breadcrumb-item">Vehicle Brands </li>
                    </a>
                    <li class="breadcrumb-item active" aria-current="page">&nbsp;/ Modify</li>
                </ol>
            </nav>
        </div>
    </div>
</div>


<div class="content">
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Modify Vehicle Brands Details</h3>
        </div>
        <div class="block-content">
            <form name="vehicleBrandInformation" id="vehicleBrandInformation" class="mb-5" action="<?php echo $this->url('admin-vehicle-brands', array('action' => 'edit')); ?>" method="post">
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="name">Name<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="text" value="<?php echo $result['vb_name']; ?>" class="form-control isRequired" id="name" name="name" placeholder="Enter the name" title="Please enter the name" onblur="checkNameValidation('vehicles_brands', 'vb_name', this, '<?php echo "vb_id##" . $result['vb_id']; ?>', 'Entered name id exist . Please enter an another name.')">
                    </div>
                    <label class="col-sm-2 col-form-label" for="slug">Slug<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <input type="text" value="<?php echo $result['vb_slug']; ?>" class="form-control isRequired" id="slug" name="slug" placeholder="Enter the slug" title="Please enter the slug" onblur="checkNameValidation('vehicles_brands', 'vb_slug', this, '<?php echo "vb_id##" . $result['vb_id']; ?>', 'Entered slug id exist . Please enter an another slug.')">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="description">Description</label>
                    <div class="col-sm-4">
                        <textarea type="text" class="form-control" id="description" name="description" placeholder="Enter the description" title="Please enter the description"><?php echo $result['description']; ?></textarea>
                    </div>
                    <label class="col-sm-2 col-form-label" for="parentId">Parent Vehicle</label>
                    <div class="col-sm-4">
                        <select class="form-control selectpicker isBootstrapSelect" data-selected-text-format="count > 3" data-live-search="true" data-container="body" data-actions-box="true" id="parentId" name="parentId" data-placeholder="Choose one parent Vehicle ..." title="Please select the parent Vehicle">
                            <?php if (isset($vehiclelist) && count($vehiclelist) > 0) {
                                foreach ($vehiclelist as $vehicle) {
                                    $selected = (isset($result['parent_id']) && $result['parent_id'] == $vehicle['vb_id']) ? "selected='selected'" : "";
                                    echo '<option value="' . base64_encode($vehicle['vb_id']) . '" ' . $selected . '>' . $vehicle['vb_name'] . '</option>';
                                }
                            } ?>
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label" for="status">Status<span class="mandatory">*</span></label>
                    <div class="col-sm-4">
                        <select class="form-control isRequired" id="status" name="status" title="Please select the Vehicle status">
                            <option value="active" <?php echo (isset($result['vb_status']) && $result['vb_status'] == 'active') ? "selected='selected'" : ""; ?>>Active</option>
                            <option value="inactive" <?php echo (isset($result['vb_status']) && $result['vb_status'] == 'inactive') ? "selected='selected'" : ""; ?>>Inactive</option>
                        </select>
                    </div>
                </div>
                <hr>
                <div class="row items-push submit">
                    <div class="col-lg-7 offset-lg-4">
                        <input type="hidden" id="vbId" name="vbId" value="<?php echo base64_encode($result['vb_id']); ?>" />
                        <a href="<?php echo $this->url('admin-vehicle-brands', array('action' => 'index')); ?>" class="btn btn-hero-dark">Cancel</a>&nbsp;
                        <button type="submit" class="btn btn-hero-primary" onclick="validateNow();return false;"><i class="fa fa-fw fa-check"></i> Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    duplicateName = true;
    $(document).ready(function() {
        $("#name").stringToSlug({
            getPut: "#slug"
        });
    });

    function validateNow() {
        flag = deforayValidator.init({
            formId: 'vehicleBrandInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('vehicleBrandInformation').submit();
            }
        }
    }

    function checkNameValidation(tableName, fieldName, obj, fnct, msg) {
        checkValue = document.getElementById(obj.id).value;
        if ($.trim(checkValue) != '') {
            $.post("<?php echo $this->url('common', array('action' => 'index')); ?>", {
                    tableName: tableName,
                    fieldName: fieldName,
                    value: checkValue,
                    fnct: fnct
                },
                function(data) {
                    if (data > 0) {
                        alert(msg, 'err');
                        duplicateName = false;
                        document.getElementById(obj.id).value = "";
                    } else {
                        duplicateName = true;
                    }
                });
        }
    }
</script>