	<!--================banner Area =================-->
	<section class="banner_area d-flex text-center">
		<div class="container align-self-center">
			<div class="row">
				<div class="col-md-12">
					<div class="banner_content">
						<h6>Welcome to</h6>
						<h1>VEHICLE TRACKING SYSTEM</h1>
						<p>Please click login button to processed with vehicle system</p>
						<a href="<?php echo $this->url('admin-home', array('action' => 'index')); ?>" class="btn_hover btn_hover_two">Login</a>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================banner Area =================-->